docker/postgres/Dockerfile
postgres/pixl-db_init.sh

Also handily means we can just apt install python
which should mean docker will cache the python installation step instead of rerunning it each build

Upgrade postgres to 16

---

pixl_ehr/src/pixl_ehr/_queries.py

Just cleaning up some old ruff issues.
Closes #157

Fix ruff rule PLW2901 "redefine loop name"

---

.gitignore

The README instructs you to create the config file with `cp pixl_config.yml.sample  pixl_config.yml` and add your sensitive credentials to the new file. However, `pixl_config.yml` was not in the `.gitignore` so it would have been very easy to accidentally put this in the repo.

Must keep live config file out of the repo!

---

cli/tests/docker-compose.yml
docker-compose.yml
pixl_core/tests/docker-compose.yml
pixl_ehr/tests/docker-compose.yml
pixl_pacs/tests/docker-compose.yml

Although I never saw this fail on GHA, this failed very frequently on my Mac, such that the system test could not be run at all.
From pacs-api log:
```
2024-01-25T16:56:18.017005033Z ConnectionRefusedError:
2024-01-25T16:56:18.017461088Z ConnectionError: 
```
From queue log:
```
2024-01-25 16:56:32.718210+00:00 [info] <0.730.0> Server startup complete; 4 plugins started.
```
Ie. connection was attempted 14 seconds before server was ready.
Given:
```
2024-01-25 18:16:46.560534+00:00 [info] <0.752.0> Server startup complete; 4 plugins started.
```
A quick experiment with the `rabbitmq-diagnostics` command showed that:
```
Thu 25 Jan 2024 18:16:45 GMT
+ docker exec 4e67f53ede32 rabbitmq-diagnostics -q check_running
Error:
RabbitMQ on node rabbit@4e67f53ede32 is not running or has not fully …
```

pacs-api container was trying to connect to rabbitmq before it was up

---

README.md
pixl_core/pyproject.toml
pixl_core/src/core/upload.py
pixl_core/tests/test_upload.py
test/scripts/check_ftps_upload.py

(This code is derived from the useful bits of #274 most of which is not needed due to a requirements change)
To make FTP upload code more robust against future changes to the file layout simply upload everything as found, with no assumptions as to layout.
Document the files present at each step of the pipeline.

FTP upload preserving directory structure

---

.github/workflows/main.yml
pytest-pixl/src/pytest_pixl/ftpserver.py

Default behaviour of github caching action is to not save to save if the workflow fails.
On passing test:
first run with caching enabled: [8m35s for entire imaging-api action](https://github.com/UCLH-Foundry/PIXL/actions/runs/7986327198?pr=313)
second run with caching enabled: [4m25s for entire imaging-api action](https://github.com/UCLH-Foundry/PIXL/actions/runs/7986432516?pr=313)
Updated the github caching action to always save cache

Try build cache on passing imaging api tests

---

cli/README.md
pixl_core/README.md
pixl_dcmd/README.md
pixl_ehr/README.md
pixl_imaging/README.md

We previously assumed `pip install -e` installed all following packages in editable mode, which is wrong.
```
pip install -e ../pixl_core .
```
which would copy the local package to the virtual environment, see pip freeze extract 
```
pixl_ehr @ file:///Users/petertsrunchev/Repositories/PIXL/PIXL/pixl_ehr
```
```
pip install -e ../pixl_core -e .
```
which correctly installs local package as editable. 
Pip freeze:
```
-e git+ssh://git@github.com/UCLH-Foundry/PIXL.git@9c6f5a62fca5296d91cb4c93f647b9f037818086#egg=pixl_ehr&subdirectory=pixl_ehr
```
This updates the docs to reflect the correct way of installing editable packages.

Correct instructions for editable installs

---

cli/src/pixl_cli/main.py
orthanc/orthanc-anon/plugin/pixl.py

The API call to export_patient_data is synchronous. Ie. it has to export the radiology parquet file, and upload all parquet files to FTP before returning via HTTP to the CLI.
Therefore the 10 second timeout on the client side is probably way too short.
I have increased it by a lot here - but the server or something in between may still cause a timeout. If so, we may have to look into sending TCP keepalives. I also increased the orthanc upload by a bit but wasn't sure if that was for a single image or something more.
What’s the biggest set of data this call has been tested with so far? I may be way overestimating how long it takes.
Synchronously waiting for some potentially unreliable tasks (eg FTP upload) to happen is probably not a great design for a distributed system like we have, but …

Increase http timeouts because export radiology + parquet upload is performed synchronously

---

.github/workflows/main.yml
docker-compose.yml
docker/orthanc-anon/Dockerfile
docker/orthanc-raw/Dockerfile
pixl_dcmd/pyproject.toml
test/docker-compose.yml

Using the new `orthancteam/orthanc` images, following their [update to Debian 12](https://github.com/orthanc-server/orthanc-builder/blob/master/release-notes-docker-images.md#2433).
This should allow us to use Python 3.11 everywhere.

Update to latest orthanc containers with Python 3.11

---

cli/pyproject.toml
pixl_core/pyproject.toml

Don't want to have to recreate another set of envs on the GAE next time we upgrade. So allowing greater than 3.10

Allow python 3.12 for cli

---

pixl_dcmd/src/pixl_dcmd/main.py
pixl_dcmd/tests/test_main.py

In preparation of #292. So we can merge the manufacturer overrides with the base tag schema.
- **Add simple test for merging multiple tag schemes**
- **Implement merging multiple tag schemes**

Allow merging multiple tag schemas

---

pixl_core/pyproject.toml
pixl_core/src/core/project_config.py
pixl_core/tests/test_project_config.py

- Optional fields are now truly optional
- Check tag op files exist
- Each test was repeatedly modifying the same test data; use a fixture instead
- Base data had some out of date field names; now validate the baseline data before trying to break anything
- Check that all production configs are valid

Various fixes to config code and tests

---

pixl_imaging/tests/conftest.py

The `imaging-api` test frequently fails on CI, because building (or waiting) for the docker containers takes longer than the specified `timeout`. Increasing `timeout` to 3 minutes to prevent this.

Increase timeout for `imaging-api` test containers

---

test/system_test.py

Several tests were being ignored in the system test.

Pytest classes cannot have an __init__ method

---

pixl_core/pyproject.toml
pixl_dcmd/src/pixl_dcmd/_database.py
pixl_dcmd/src/pixl_dcmd/main.py
pixl_dcmd/tests/conftest.py

This should allow running multiple projects with the same or overlapping studies without having to
tear down and rebuild the entire setup.
Necessary for #379.

Include `project_slug` in Image PIXL database queries

---

pixl_imaging/tests/docker-compose.yml

I noticed the imaging test was failing intermittently. The error occurs when trying to upload test data with curl. It wasn't waiting for orthanc to be up before running this command.
Running pytest on command line:
Without fix:
Failed 8 times out of 100
With fix:
Failed 0 times out of 100

Add healthchecks to orthanc servers in imaging test

---

docker-compose.yml
pixl_core/tests/docker-compose.yml
pixl_export/tests/docker-compose.yml
pixl_imaging/tests/docker-compose.yml
test/docker-compose.yml

Partially addresses #239 (fixing rather than auditing)
Most open ports only need to be accessed from the CLI that's running on the same host. So only listen on localhost.
Similar principal applies to running tests, although those usually won't be run in the hospital.
Orthanc raw and anon are a notable exception as someone may want to view those from the DSD or another hospital computer, but otherwise exposing everything to (perhaps) the whole hospital is a security hazard.

Don't expose ports on all interfaces unless needed

---

cli/src/pixl_cli/_database.py
cli/src/pixl_cli/main.py
cli/tests/conftest.py
cli/tests/test_database.py
hasher/tests/conftest.py
pixl_core/tests/conftest.py
pixl_core/tests/uploader/test_dicomweb.py
pixl_export/tests/conftest.py
ruff.toml
test/conftest.py
test/utils.py

attempt at solving the second definition of done cirteria, closes https://github.com/UCLH-Foundry/the-rolling-skeleton/issues/250

feat[cli]: only export linker information for processed images

---

pixl_core/src/core/project_config/pixl_config_model.py
pixl_core/src/core/project_config/tag_operations.py
pixl_core/tests/project_config/test_project_config.py
pixl_dcmd/src/pixl_dcmd/_tag_schemes.py
pixl_dcmd/tests/test_main.py
pixl_dcmd/tests/test_tag_schemes.py
projects/configs/ms-pinpoint-internal-only.yaml
projects/configs/tag-operations/manufacturer-overrides/mri-diffusion.yaml
projects/configs/tag-operations/manufacturer-overrides/mri.yaml
projects/configs/test-extract-uclh-omop-cdm-dicomweb.yaml
projects/configs/test-extract-uclh-omop-cdm.yaml
projects/configs/uclh-prostate-mri-validation-dataset.yaml

Feedback from Prostate MRI is that some public tags can have rounding issues, so including private tags. Not sure if its worth just creating a separate override for mri's as a whole?
closes https://github.com/UCLH-Foundry/the-rolling-skeleton/issues/245

Add in extra private tags for philips

---

cli/pyproject.toml
hasher/pyproject.toml
pixl_core/pyproject.toml
pixl_dcmd/pyproject.toml
pixl_export/pyproject.toml
pixl_imaging/pyproject.toml
pytest-pixl/pyproject.toml

* Bump module versions to `0.2.0-rc` following the [v0.1.0 release](https://github.com/UCLH-Foundry/PIXL/releases/tag/v0.1.0)
* Update dependency pins for `pixl_core` and `pytest_pixl` to `>=0.1.0`
Closes #473

Set development version

---

cli/src/pixl_cli/_config.py
cli/src/pixl_cli/_message_processing.py
cli/src/pixl_cli/main.py
cli/tests/test_message_processing.py
cli/tests/test_messages_from_files.py
pixl_core/src/core/exceptions.py
pixl_core/src/core/patient_queue/subscriber.py
pixl_core/src/core/token_buffer/tokens.py
pixl_core/tests/patient_queue/test_subscriber.py
pixl_core/tests/token_buffer/test_tokens.py
pixl_export/tests/test_app.py
pixl_imaging/README.md
pixl_imaging/src/pixl_imaging/_processing.py
pixl_imaging/src/pixl_imaging/main.py
pixl_imaging/tests/test_imaging_processing.py

Fixes https://github.com/SAFEHR-data/the-rolling-skeleton/issues/416
- add a second queue (`_imaging_secondary`) for querying PACS
- messages processed by the existing `imaging` queue will only query the VNA. If a study is not available in the VNA, the corresponding message will be published to the new secondary imaging queue
- messages are only processed by the secondary imaging queue outside of working hours (as we don't want to query PACS during working hours)

Add a separate queue for querying PACS

---

pixl_imaging/src/pixl_imaging/_processing.py

That way don't have INFO level logs of processing messages from secondary queue before 8pm

Check secondary hours before logging processing

---

pixl_imaging/src/pixl_imaging/_orthanc.py

If a job is pending for a long time then it can timeout currently, which shouldn't happen

Reset start time if pending status

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/pull_request_template.md
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
docs/design/bigger_picture.md
schemas/github-issue-forms.json

Fixes #481: Improving readability and reproducibility, including:
* Fixed templates for issues and PR
* Adds .pre-commit-config.yaml with schemas/github-issue-forms.json to check templates
* Adds note for links that are not open to the public by essentially requesting access with a new issue
* Adds collapsed sections to improve readability of main README

481 - Improving readability and reproducibility of the repo

---

.renovaterc.json5
orthanc/orthanc-anon/config/orthanc.json
orthanc/orthanc-anon/plugin/download_dicom_spec.py
orthanc/orthanc-anon/plugin/pixl.py
orthanc/orthanc-raw/config/orthanc.json
orthanc/orthanc-raw/plugin/pixl.py
pixl_core/src/core/dicom_tags.py
pixl_core/src/core/uploader/_ftps.py
pixl_core/src/core/uploader/_orthanc.py
pixl_core/src/core/uploader/_xnat.py
pixl_core/src/core/uploader/base.py
pixl_core/tests/uploader/test_base.py
pixl_core/tests/uploader/test_dicomweb.py
pixl_core/tests/uploader/test_xnat.py
pixl_dcmd/README.md
pixl_dcmd/src/pixl_dcmd/_database.py
pixl_dcmd/src/pixl_dcmd/_dicom_helpers.py
pixl_dcmd/src/pixl_dcmd/main.py
pixl_dcmd/tests/conftest.py
pixl_dcmd/tests/test_dicom_validator.py
pixl_dcmd/tests/test_main.py
pixl_export/src/pixl_export/main.py
pixl_imaging/src/pixl_imaging/_orthanc.py
pixl_imaging/src/pixl_imaging/_processing.py
pixl_imaging/tests/orthanc_raw_config/orthanc.json
projects/configs/tag-operations/base.yaml
projects/configs/tag-operations/test-external-user.yaml
projects/configs/tag-operations/test-extract-uclh-omop-cdm.yaml
projects/configs/tag-operations/uclh-nasogastric-tube-project-ngt-only-full-dataset.yaml
test/system_test.py

Fixes #526
- remove the private DICOM tag for the PIXL project name. Instead, pass the project name in the payload to the Orthanc Anon plugin and export API
- simplify `pixl_dcmd.main.anonymise_dicom` - move the config loading and db updating into separate functions (happy to move into a separate PR if it's confusing things here)
- update tests to reflect changes

Remove private DICOM tag for PIXL project name

---

pixl_imaging/src/pixl_imaging/_orthanc.py
pixl_imaging/src/pixl_imaging/_processing.py

Fixes #531
- use the DICOM timeout when getting info on the instances in a study
- when determining if there are any instances missing, first get statistics of the study and compare the number of local and remote instances (if all instances are present locally there's no need to get the list of `SOPInstanceUIDs`)

Fix timeout issues when querying instances of a local study in Orthanc

---

projects/configs/ion-neuro-db.yaml
projects/configs/prognosis-ai.yaml
projects/configs/tag-operations/ion-neuro-db.yaml

Creating default configuration for IoN Neuro DB project. 
We override sequentually so the first file to be read is the
- [projects/configs/tag-operations/base.yaml](https://github.com/SAFEHR-data/PIXL/blob/main/projects/configs/tag-operations/base.yaml)
- then [projects/configs/tag-operations/mri.yaml](https://github.com/SAFEHR-data/PIXL/blob/main/projects/configs/tag-operations/mri.yaml)
- and specific to this project: [projects/configs/tag-operations/ion-neuro-db.yaml](https://github.com/SAFEHR-data/PIXL/blob/main/projects/configs/tag-operations/ion-neuro-db.yaml)
- Then for specific manufacturers: [projects/configs/tag-operations/manufacturer-overrides/mri.yaml](https://github.com/SAFEHR-data/PIXL/blob/main/projects/configs/tag-operations/manufacturer-overrides/mri.yaml)

Add configuration for IoN Neuro DB project

---

pixl_core/src/core/uploader/_ftps.py

Fixes #589
- always try to create the folder and ignore the exception if it already exists. Previously we would check for existence and create it if necessary. But we sometime attempted to create the same folder twice during concurrent uploads

Fix intermittent system tests failure caused by creating the output directory twice

---

pixl_dcmd/tests/test_main.py

Fixes #193:
This PR adds a unit test to `pixl_dcmd` which creates three DICOM datasets, 2 which match the modalities field within `test_project_config` and 1 which does not match. The test uses the `anonymise_dicom()` function and confirms that the "MR" dataset is dropped because it is not in the project config. 
It also asserts true the modalities within the config, and asserts not true modalities omitted from the config.

Adds test to check modalities not specified in project config are dropped

---

.env.sample
cli/README.md
cli/src/pixl_cli/_docker_commands.py
docker-compose.yml
test/.env
test/docker-compose.yml
test/run-system-test.sh

Fixes #597 
- Remove use of profiles with docker compose
- Always expose the `CLI_PIXL_DB_PORT` on the postgres container
- Remove `EXTERNAL_PIXL_DB` env var as we're no longer using profiles
- Remove second postgres container used in integration tests; use the same postgres instance for PIXL DB and Orthanc Raw
- We can still have PIXL DB running in an external postgres instance (by setting the relevant env vars), but we're not testing for this in CI
- Update docs to reflect changes
- tested on dev instance on GAE
Fixes #{issue_number}: A few words or sentences describing the changes proposed in this pull request (PR).

Add support for Docker Compose<22.0

---

pixl_imaging/src/pixl_imaging/_orthanc.py
pixl_imaging/src/pixl_imaging/_processing.py

Fixes #604 
- add a function `pixl_imaging._orthanc.Orthanc.get_remote_query_instances` that takes a `query_id` and re-submits the same query but at the `Instance` level
- remove `pixl_imaging._orthanc.Orthanc.get_remote_query_answer_instances`
- update `pixl_imaging._processing._get_missing_instances` to use the new function `get_remote_query_instances`
Edit: the above doens't work on the GAE as the VNA still complains that there is no `SeriesInstanceUID` in the instances query
Instead:
- use the `"/queries/{query_id}/answers/{answer_id}/query-seroes"` to get a list of the series in the study
- iterate over the series, and use the `"/queries/{query_id}/answers/{answer_id}/query-instances"` to get a list of the instances in each series

Get remote query instances by recreating the query at the Instance level
