pixl_ehr/src/pixl_ehr/_queries.py
I think this unbreaks things but I may have misunderstood what this code is supposed to do.
=> Fix error in placeholder substitution

orthanc/orthanc-anon/plugin/tag-operations.yaml
Keeping in [Exposure time](
https://dicom.innolitics.com/ciods/ct-image/ct-image/00181150) as that's how long the exposure was
Closes #224
=> Remove dates, time and datetimes tags from DICOM

pixl_pacs/README.md
- Remove mentions of PACS
- Clarify confusing sentence
We're missing a description of what a *VNA* is somewhere.
=> Update Imaging API README

pixl_pacs/src/pixl_pacs/_processing.py
Artefact from copying over EHR API docstrings
=> Fix docstring of `ImagingStudy` class

orthanc/orthanc-anon/plugin/tag-operations.yaml
Reduce amount of data exposed, date of birth will be iven in OMOP ES data
=> Remove dicom age

.github/ISSUE_TEMPLATE/voxl.yml
- Update template to be for VOXL (though maybe this naming will change?)
- use checklists under headings to try and make checklists a default choice when filling
=> Update PR template for VOXL milestone

orthanc/orthanc-anon/README.md
Closes #295 
Already implemented I just didn't take the time to read the code fully 🤦
=> Document commenting out of azure dicom connection

.pre-commit-config.yaml, README.md, bin/linters/check_headers_exist.sh
Run only on git-staged files
Fixing my overenthusiastic merge of  #317
=> Fix the copyright heading linter

docker/imaging-api/Dockerfile, docker/orthanc-anon/Dockerfile, docker/orthanc-raw/Dockerfile, pixl_dcmd/pyproject.toml
Its quite a slow step for building, locally doesn't seem to be needed
=> Remove pip tools

test/test_radiology_parquet.py
This was failing on my dev machine.
=> Refer to specific rows in the dataframe; don't assume order

orthanc/orthanc-anon/README.md, orthanc/orthanc-raw/README.md, pixl_imaging/tests/docker-compose.yml
Fixes #308 by updating READMEs and image used for pixl_imaging tests.
=> Remove final osimis references

docker/.dockerignore, docker/ehr-api/Dockerfile, docker/hasher-api/Dockerfile, docker/imaging-api/Dockerfile, docker/orthanc-anon/Dockerfile, docker/orthanc-raw/Dockerfile
=> Force reinstallation of PIXL modules in Docker containers

pixl_imaging/pyproject.toml
Fix
https://github.com/UCLH-Foundry/PIXL/security/dependabot/4
https://github.com/UCLH-Foundry/PIXL/security/dependabot/5
=> bump aiohttp version, fix dependabot alerts

docs/setup/azure-keyvault.md
Dave let us know that the tenant wasn't what we had documented
=> Document correct prod tenant

cli/pyproject.toml, hasher/pyproject.toml, pixl_core/pyproject.toml, pixl_dcmd/pyproject.toml, pixl_export/pyproject.toml, pixl_imaging/pyproject.toml, pytest-pixl/pyproject.toml
Bump versions of all modules to `0.1.0`.
Part of #473
=> Release 0.1.0

cli/README.md, cli/src/pixl_cli/_database.py, cli/src/pixl_cli/_io.py, cli/src/pixl_cli/_message_processing.py, cli/tests/test_database.py, cli/tests/test_messages_from_files.py, pytest-pixl/src/pytest_pixl/data/omop-resources/multiple_projects.csv
Fixes #466 
- update `filter_exported_or_add_to_db` to handle filtering and adding images for multiple projects
- add function `filter_exported_or_add_to_db_for_project` to filter messages and add images for a single project
- add test case with CSV file that contains multiple projects
- update CLI docs to mention multiple projects can be defined in a CSV file
#466 also mentions that an error should be raised if omop input contains multiple projects, but as far as I can tell this is not possible as the project name [comes from the `extract_summary.json`](https://github.com/UCLH-Foundry/PIXL/blob/76b6a5f9142d894343fa22a8dd29ecca34ea952d/cli/src/pixl_cli/_io.py#L43). Is it possible that this field contains multiple project names, or is there another way omop input could contain multiple …
=> Add support for multiple projects in CSV file

cli/src/pixl_cli/_message_processing.py, cli/src/pixl_cli/main.py, cli/tests/conftest.py, cli/tests/test_message_processing.py
Fixes #478 
- remove `project_name` argument from `retry_until_export_count_is_unchanged` and update `new_last_exported_count` to check number of images from all projects in the messages 
=> Update `retry_until_export_count_is_unchanged` to handle messages from multiple projects 

orthanc/orthanc-anon/plugin/pixl.py, pixl_core/src/core/project_config/pixl_config_model.py, pixl_dcmd/README.md, pixl_dcmd/pyproject.toml, pixl_dcmd/ruff.toml, pixl_dcmd/src/pixl_dcmd/__init__.py, pixl_dcmd/src/pixl_dcmd/main.py, pixl_dcmd/src/pixl_dcmd/tagrecording.py, pixl_dcmd/tests/test_main.py, projects/configs/tag-operations/test-external-user.yaml, projects/configs/test-external-user.yaml
If we want someone to use our anonymisation externally, this allows them to do this without having to have a pixl database setup. Defaults don't change any behaviour.
Also some general code clean up. 
=> Allow dicom anonymisation from external users

docker-compose.yml, pixl_core/pyproject.toml, test/conftest.py, test/system_test.py
Toward #465 
This doesn't fix the tests, but makes them easier to debug and gives us more info when the tests do fail. I couldn't reproduce the failing test locally so haven't applied the fix until we understand what the issue is.
- use `pytest-check` to ensure we always test both zip files in `test_ftps_dicom_upload` (previously the test will stop as soon as the first assert failed)
- log which zip file and procedure we are testing in `test_ftps_dicom_upload` 
- add a fixture to cleanup the pixl database after running system tests. This allows system tests to be rerun locally. Previously, when rerunning the system tests, no data would be exported as was already exported on the previous run
=> Make it easier to debug flaky system tests

cli/pyproject.toml, hasher/pyproject.toml, pixl_core/pyproject.toml, pixl_dcmd/pyproject.toml, pixl_export/pyproject.toml, pixl_imaging/pyproject.toml, pytest-pixl/pyproject.toml
Fixes #428 
- remove duplicated transitive dependencies and depend on `core` and `core` extras (`dev` and `test`) where appropriate
=> Tidy up dependencies

cli/README.md, cli/src/pixl_cli/_message_processing.py, cli/src/pixl_cli/main.py, cli/tests/test_message_processing.py, cli/tests/test_messages_from_files.py, cli/tests/test_populate.py, pixl_core/src/core/patient_queue/_base.py, pixl_core/src/core/patient_queue/producer.py, pixl_core/src/core/patient_queue/subscriber.py, pixl_core/tests/patient_queue/test_producer.py, pixl_core/tests/patient_queue/test_subscriber.py
Fixes #472: Use a priority queue to allow for high priority populating of studies
- set `"x-max-priority": 5` when creating a queue (the value [recommended](https://www.rabbitmq.com/docs/priority#overview) in RABBITMQ docs for priority queues). Higher values are higher priority
- add `--priority` argument to the `populate` cli command for setting the priority of messages
- update tests to set priority of messages
- update docs to explain how to set the priority of messages
=> Use a priority queue

.github/workflows/main.yml, orthanc/orthanc-raw/config/dicom.json, pixl_imaging/src/pixl_imaging/_orthanc.py, pixl_imaging/tests/docker-compose.yml, pixl_imaging/tests/orthanc_raw_config/dicom.json, pixl_imaging/tests/orthanc_raw_config/orthanc.json, pixl_imaging/tests/test_imaging_processing.py
Related to #486.
- For #486, we need to compare the `SOPInstanceUID`s in Orthanc Raw against those in the VNA / PACS. However, when retrieving data, the `StudyInstanceUID`, and `SeriesInstanceUID`, and `SOPInstanceUID` values are modified by Orthanc Raw.
Fixes #496 
- keep `StudyInstanceUID`, `SeriesInstanceUID`, and `SOPInstanceUID` when setting the project name private tag in Orthanc Raw. Also set `Force=True` to allow us to keep these UIDs
- set `OverwriteInstance: True` in the PIXL Raw config so that if an instance with an existing SOPInstanceUID is uploaded, the previous instance is overwritten (otherwise we'd need to manually delete the old instance after setting the project name tag)
- Add test to check the `StudyInstanceUID`, `SeriesInstanceUID`, and `SOPInstanceUID` are correct …
=> Check the study UID in Orthanc Raw is the same as in VNA / PACS [force-system-test]

orthanc/orthanc-raw/config/dicom.json, pixl_imaging/src/pixl_imaging/_orthanc.py
Found a lot of timeout when running, expect this should fix them but will leave this running for a day to check. 
=> Use DICOM timeout for getting answer instances

orthanc/orthanc-anon/plugin/pixl.py, pixl_dcmd/src/pixl_dcmd/_dicom_helpers.py
#512  introduced a bug in the Orthanc Anon plugin whereby studies are always exported - this PR fixes that bug
- check the value of `should_export()` before calling `Send()` in the Orthanc Anon plugin
- improve logging in the Orthanc Anon plugin
=> Only export to endpoint if AUTOROUTE_ANON_TO_ENDPOINT is `true`
